### ISSUE TITLE
Adding pilz_industrial_motion to this repo

### ISSUE THREAD

**Issue by davetcoleman** [ros-planning/moveit#1800]
Moving https://github.com/PilzDE/pilz_industrial_motion/issues/228 discussion here.

We have been talking with Pilz, and they have agreed, to further integrate [their industrial planners](https://github.com/PilzDE/pilz_industrial_motion) (generators to create LIN, PTP and CIRC trajectories) into the MoveIt project by merging their planners here.

**Benefits**
- More users / exposure of their great work to the MoveIt community
- Fill a much needed gap in MoveIt's feature set for classic industrial interpolation approaches to planning
- Reduce duplicate maintenance by including code cleanup, releasing, upgrading code, and general community policy into the MoveIt maintainer project
- Increase MoveIt's test coverage (as measured by the [new CodeCov](https://github.com/ros-planning/moveit_ci/pull/91)!) by including Pilz's very feature rich test coverage
- Include more companies (Pilz) in the development of MoveIt 

**TODO**
- [ ] Decide on name for this new planner (``industrial_planner`` was suggested by Pilz in meeting, but they are open to renaming)
- [ ] Add @jspricke as a MoveIt maintainer so he can continue to maintain this feature. I think he has proven his skills with the development of pilz_industrial_motion
- [ ] Add @ct2034 as a MoveIt Core Contributor so he can also get more involved in maintenance
- [ ] Create PR to merge into ``master`` branch
- [ ] Backport PR to ``melodic``
- [ ] Optional: Backport PR to ``kinetic``? In our meeting it was not clear if this is necessary. Personally on further thought, I don't think it's worth it.
- [ ] Create moveit_tutorial for this new planner
- [ ] Create blog post about this collaboration

**Comment by jspricke** [comment]
Hey @davetcoleman, thanks for the offer but I guess you don't mean me ;).

**Comment by gavanderhoorn** [comment]
Much of the Pilz work is GPLv3, which is not something we'd want to import into MoveIt. Changing licenses is possible, but would require an OK from all contributors.

Additionally: `pilz_industrial_motion` has been supported by the ROSIN project, which leads to a requirement for Pilz to make sure maintenance and access to the results are guaranteed up to a certain nr of years. Has this been discussed as well?

**Comment by ct2034** [comment]
@davetcoleman thanks for the beautiful summary! But please change the user handle to @jschleicher.

**Comment by ct2034** [comment]
And I want to add
( ) make @jschleicher and @ct2034 code owners

**Comment by davetcoleman** [comment]
Sorry @jspricke for tagging the wrong name! Fixed.

**Comment by davetcoleman** [comment]
@gavanderhoorn I had not realized its GPLv3, that is very concerning!

**Comment by davetcoleman** [comment]
@jschleicher any update on changing the license of pilz_industrial_motion to non-copy left?

**Comment by jschleicher** [comment]
@davetcoleman Yep, we'll change the license of the affected `pilz_trajectory_generation` package. Starting to work on that we'll post a PR soon @ct2034

**Comment by davetcoleman** [comment]
@jschleicher did this get backported to Melodic as desired?
