### ISSUE TITLE
Noetic Ninjemys Release

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit#2015]
### Pre-Release Noetic Release Tasks:
- [ ] Get upstream packages released: [link to list](http://repositories.ros.org/status_page/blocked_releases_noetic.html?q=id%3D%22moveit%22&s=6&r=1) (ignore orocos)
  - [x] ompl @mamoll 
  - [x] srdfdom @tylerjw
  - [x] rosparam_shortcuts @JafarAbdi 
  - [ ] For moveit_servo:
    - [ ] [ros_pytest](https://github.com/machinekoder/ros_pytest) @rhaschke pinged them: https://github.com/machinekoder/ros_pytest/pull/5#issuecomment-650788937
    - [x] [joystick_drivers](https://github.com/ros-drivers/joystick_drivers/issues/170)  (need spacenav for jogarm) @mikeferguson will ping them
    - [x] [joy_teleop](https://github.com/ros-teleop/teleop_tools/issues/51) (for jogarm) @davetcoleman has pinged them
  - [ ] moveit_resources: requires https://github.com/ros-planning/moveit_resources/pull/29
  - [ ] tf2: https://github.com/ros/geometry2/pull/471
  - [ ] [franka_description](https://github.com/frankaemika/franka_ros/issues/104) for tutorials @davetcoleman 
- [x] Create temporary [.rosinstall](https://github.com/ros-planning/moveit/blob/master/moveit_noetic.rosinstall) file for building moveit will all required source builds @davetcoleman 
- [ ] Python code ported to be python3 compatible: [guide](http://wiki.ros.org/UsingPython3)
  - [x] [Progress PR](https://github.com/ros-planning/moveit/pull/2131) @mikeferguson 
- [ ] Travis tests on 20.04 with python3 - @tylerjw 
  - [ ] [`catkin tools` is broken](https://github.com/catkin/catkin_tools/issues/603): Travis installs from source as a workaround.
  - [x] Noetic Docker images #2132 / #2178
  - [x] `clang-format-3.9` is not available in `Ubuntu Focal`. The newer clang-format-10 reformats virtually everything: #2169.
- [ x] ~noetic_devel branches for moveit, moveit_tutorials, moveit_msgs - @davetcoleman (waiting until June 15th to start branching)~  Decided in Working Group meeting we won't branch for Noetic, just keep using master
- [ ] Testing and Dog-fooding on on 20.04 @JafarAbdi 

### Release Tasks
- [ ] Write release notes @tylerjw 
- [ ] Bloom / rosdistro updates @tylerjw 
- [ ] Kick off release build @tylerjw 
- [ ] Discourse announcement 

Please comment with issue links and I'll update the main description here to have a checklist of tasks needed to cut the Noetic release.

Here is the migration page to help with getting up to date with the latest changes and what we might need to change in MoveIt to be compatible: http://wiki.ros.org/noetic/Migration

**Comment by rhaschke** [comment]
One major point for Noetic migration is the transition to Python3. @v4hn and his group have already done a lot of work into this direction. However, I'm not sure about the current state.
Another major point is to have all the upstream packages released beforehand. OSRF is gently pushing maintainers to do so... [Here](http://repositories.ros.org/status_page/blocked_releases_noetic.html?q=id%3D%22moveit%22&s=6&r=1) is the list of blocking packages.

**Comment by v4hn** [comment]
On Tue, Apr 07, 2020 at 03:29:35PM -0700, Robert Haschke wrote:
> One major point for Noetic migration is the transition to Python3.
> @v4hn and his group have already done a lot of work into this direction.
> However, I'm not sure about the current state.

I sent small patches for python2/3 compatibility in the past, but only for problems I actually encounter.
And I do not use the python APIs a lot.

I believe there are quite a few undetected issues still lingering around.

CI support for noetic and an extended python test suite would help a lot.

**Comment by davetcoleman** [comment]
Thanks @tylerjw for creating this issue! 
I've just [updated the homepage](https://github.com/ros-planning/moveit.ros.org/pull/438) with a target release date of June 19th, which is roughly 1 month after the ROS distro comes out. Aspirational maybe...

I think a good next step is to ask people to volunteer various tasks, and we put their user names next to the checkbox items above. I'm happy to take on branching the moveit_tutorials, and can branch everything else also if needed. I've done this in the past.

>  Populate this list with bugs that need squashed

This seems idealistic and not a necessary blocker for getting Noetic out on time. Focusing on required things like Python3 is enough scope already, no?

**Comment by tylerjw** [comment]
> This seems idealistic and not a necessary blocker for getting Noetic out on time. Focusing on required things like Python3 is enough scope already, no?

The list doesn't have to be extensive.  The intent of that bullet to make sure we scope out the bugs that we will fix before the release to avoid us slipping on the release because we want to wait for just-one-more-thing.  My goal was to figure out exactly what the work involved was so it was easier to defend against scope creep.  Fixing Python3 compatibility is a feature we'll need for this and if we agree that is the scope of fixes I'll mark this one as complete.

I'll put you down for the branching and take the responsibility of CI infrastructure changes to run in 20.04.  This should find all the areas where we have existing testing of python code that isn't python3 compatible yet.

**Comment by tylerjw** [comment]
> Finally, we need to find a new clang-format configuration as clang-format-3.9 is not available anymore in Focal and newer versions reformat virtually everything using the current config.

Should we make this the point where we apply google style clang-format to moveit.  That would make keeping future changes in sync with ROS2 development nicer as ROS2 could start using ament_clang_foramt which has this .clang-format file: https://github.com/ament/ament_lint/blob/master/ament_clang_format/ament_clang_format/configuration/.clang-format

**Comment by rhaschke** [comment]
I think we should keep the formatting changes as minimal as possible. If ament_lint supports clang-format, I guess/hope that the can handle custom `.clang-format` files as well!
I already made the clang-format-10 transition for rviz: https://github.com/ros-visualization/rviz/commit/ebfbb1f5e3281f969966dc9c305b5afc444cb79c

**Comment by tylerjw** [comment]
Oh, that doesn't seem so bad.  I had assumed based on your statement that it would be a huge change.  If you think the same .clang-format you used for rviz will work we should apply it here and switch to clang-format-10 on master.

**Comment by rhaschke** [comment]
We need to try the clang-format config here and check whether we can further tweak it to reduce reformatting.

**Comment by davetcoleman** [comment]
When should we start forking the branches and tutorials? We are currently scheduled for the [feature freeze on 1 July 2020](https://moveit.ros.org/), but we probably need the branches created before then to include various changes? 

Ideally we just work out of master until that point, IMHO. We might have to use pragmas to keep support for Melodic.

To make this manageable, we should probably drop support for Kinetic on ``master`` now.

**Comment by mikeferguson** [comment]
I've created a PR for python3-pyassimp key to rosdistro: https://github.com/ros/rosdistro/pull/25263

**Comment by mikeferguson** [comment]
This should take care of the rosdep keys needed for Noetic/Python3 as well as the orocos_kdl rosdep key change (it's a system dependency now): https://github.com/ros-planning/moveit/pull/2131

**Comment by davetcoleman** [comment]
I've emailed Ruben and created this Github issue: https://github.com/orocos/orocos_kinematics_dynamics/issues/252

**Comment by mikeferguson** [comment]
> I've emailed Ruben and created this Github issue: [orocos/orocos_kinematics_dynamics#252](https://github.com/orocos/orocos_kinematics_dynamics/issues/252)

@davetcoleman Orocos_kdl is now a system dependency - it will not be released as a ROS package in noetic, so the rosdep key has changed and the blocked releases page lies (but the fix we need is in #2131).

I just finished successfully building moveit on Noetic - will post shortly how it actually runs

**Comment by mikeferguson** [comment]
Blocked releases page is a little out of date (since orocos_kdl is a system dependency now, and we have added some dependencies since the last melodic release):
 * [ ] ompl
 * [ ] srdfdom
 * [ ] rosparam_shortcuts
 * [ ] ros_pytest

**Comment by mikeferguson** [comment]
So far I've tested the following (in a source install directly on 20.04):

 * running moveit_setup_assistant (both from an existing config and a new config from URDF) - OK
 * running the demo.launch generated - this doesn't work - get the following error (but it might be my config - maybe something isn't setup right?):
   ```
   load_parameters: unable to set parameters (last param was [/move_group/planning_scene_monitor/publish_transforms_updates=True]): cannot marshal None unless allow_none is enabled
   ```
 * running move_group.launch, starting RVIZ, and using a MotionPlanning plugin to generate some movements - OK.

**Comment by davetcoleman** [comment]
Regarding orocos, its actually in the Noetic Migration Guide:
http://wiki.ros.org/noetic/Migration#Use_Orocos_KDL_and_BFL_rosdep_keys

**Comment by davetcoleman** [comment]
@rhaschke your comment in the top description is outdated I believe. Correct?

> There are no official Noetic docker images available yet, but I manually prepare one: moveit/ros:noetic.

I'm using ``ros:noetic-ros-base``

Also, I started working on the Docker PR because I wanted to test Noetic without upgrading / partitioning my system, but then I noticed you said in this issue that you had already started working on it. My bad. I don't see a PR from you, but I hope we can synchronize our work...

**Comment by JafarAbdi** [comment]
> Blocked releases page is a little out of date (since orocos_kdl is a system dependency now, and we have added some dependencies since the last melodic release):
> 
> * [ ]  ompl
> * [ ]  srdfdom
> * [ ]  rosparam_shortcuts
> * [ ]  ros_pytest
> * [ ]  joystick_drivers repo (need spacenav for jogarm)
> * [ ]  joy_teleop from https://github.com/ros-teleop/teleop_tools (for jogarm)
> 
> (also, if you aren't on shadow-fixed, geometric_shapes needs to be built from source)

Just released rosparam_shortcuts https://github.com/ros/rosdistro/pull/25273

**Comment by rhaschke** [comment]
Noetic docker images became available just recently: https://discourse.ros.org/t/ros-noetic-ninjemys-release/14262/3

**Comment by davetcoleman** [comment]
Using the [experimental docker build](https://github.com/ros-planning/moveit/pull/2132), rosdep is failing for all the following dependencies:

```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
mouse_teleop: No definition of [python-numpy] for OS version [focal]
franka_example_controllers: Cannot locate rosdep definition for [libfranka]
franka_hw: Cannot locate rosdep definition for [libfranka]
franka_control: Cannot locate rosdep definition for [libfranka]
moveit_commander: No definition of [python-pyassimp] for OS version [focal]
franka_visualization: Cannot locate rosdep definition for [libfranka]
franka_gripper: Cannot locate rosdep definition for [libfranka]
moveit_core: Cannot locate rosdep definition for [orocos_kdl]
moveit_ros_planning_interface: No definition of [python] for OS version [focal]
moveit_kinematics: Cannot locate rosdep definition for [orocos_kdl]
```

@mikeferguson did you work on these already?

**Comment by mikeferguson** [comment]
#2131 addresses the orocos_kdl, python-pyassimp ones (although also depends on rosdep being merged which is what's holding up 2131).

I did not address python-numpy for mouse_teleop (I just noticde I catkin_ignored that package). Also didn't do anything with franka

**Comment by mikeferguson** [comment]
mouse_teleop is addressed in https://github.com/ros-teleop/teleop_tools/pull/52

**Comment by mikeferguson** [comment]
Finally ran full tests for moveit repo, here's the output:
```
test_results/moveit_commander/rostest-test_python_moveit_commander.xml: 1 tests, 0 errors, 1 failures, 0 skipped
test_results/moveit_commander/rostest-test_python_moveit_commander_ns.xml: 1 tests, 0 errors, 1 failures, 0 skipped
test_results/moveit_commander/rostest-test_python_time_parameterization.xml: 1 tests, 0 errors, 1 failures, 0 skipped
test_results/moveit_core/gtest-test_bullet_continuous_collision_checking.xml: 8 tests, 0 errors, 0 failures, 2 skipped
test_results/moveit_ros_perception/gtest-mesh_filter_test.xml: 48 tests, 0 errors, 2 failures, 0 skipped
test_results/moveit_ros_planning_interface/MISSING-rostest-test_move_group_interface_cpp_test.xml: 1 tests, 0 errors, 1 failures, 0 skipped
test_results/moveit_ros_planning_interface/MISSING-rostest-test_subframes_test.xml: 1 tests, 0 errors, 1 failures, 0 skipped
test_results/moveit_ros_planning_interface/rostest-test_python_move_group.xml: 1 tests, 0 errors, 1 failures, 0 skipped
test_results/moveit_ros_planning_interface/rostest-test_python_move_group_ns.xml: 2 tests, 0 errors, 2 failures, 0 skipped
test_results/moveit_ros_planning_interface/rostest-test_robot_state_update.xml: 1 tests, 0 errors, 1 failures, 0 skipped
test_results/moveit_ros_planning_interface/rosunit-cleanup_tests.xml: 2 tests, 0 errors, 1 failures, 0 skipped
Summary: 521 tests, 0 errors, 12 failures, 2 skipped
```
Mostly python, gonna dig into a few.

**Comment by mikeferguson** [comment]
It looks like all the moveit_commander and moveit_ros_planning_interface tests are failing because the python bindings are missing a symbol. The import of:

    from moveit_ros_planning_interface import _moveit_move_group_interface

causes a missing symbol for void tf2::fromMsg<geometry_msgs::Quaternion_<std::allocator<void> >, Eigen::Quaternion<double, 0> >(geometry_msgs::Quaternion_<std::allocator<void> > const&, Eigen::Quaternion<double, 0>&)

**Comment by rhaschke** [comment]
Looks like `#include <tf2_eigen/tf2_eigen.h>` is missing somewhere.

**Comment by mikeferguson** [comment]
Mesh filter bug looks more significant:
```
[ RUN      ] float_test/MeshFilterTestFloat.float/7
/home/ubr/noetic/moveit/test/src/moveit/moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp:234: Failure
The difference between filtered_depth[idx] and gt_depth[idx] is 3.599998950958252, which exceeds 1e-6, where
filtered_depth[idx] evaluates to 3.599998950958252,
gt_depth[idx] evaluates to 0, and
1e-6 evaluates to 9.9999999999999995e-07.
```

**Comment by rhaschke** [comment]
The mesh filter bug is an old friend, only occurring with libMesa... (see #374, partially fixed in #1661, #2044). Now the deviation looks more severe. Maybe a new issue with libMesa?

**Comment by davetcoleman** [comment]
I just did a summary of Noetic Docker failures, in this PR:
https://github.com/ros-planning/moveit/pull/2132#issuecomment-638250671

I emailed my contact at Franka to push on that side.

**Comment by gleichdick** [comment]
> It looks like all the moveit_commander and moveit_ros_planning_interface tests are failing because the python bindings are missing a symbol. The import of:
> 
> ```
> from moveit_ros_planning_interface import _moveit_move_group_interface
> ```
> 
> causes a missing symbol for void tf2::fromMsg<geometry_msgs::Quaternion_<std::allocator >, Eigen::Quaternion<double, 0> >(geometry_msgs::Quaternion_<std::allocator > const&, Eigen::Quaternion<double, 0>&)

Have a look at #1785 and ros/geometry2#430.

**Comment by mamoll** [comment]
ompl release PR: https://github.com/ros/rosdistro/pull/25302

**Comment by henningkayser** [comment]
> We need to try the clang-format config here and check whether we can further tweak it to reduce reformatting.

Picked this up in #2169

**Comment by davetcoleman** [comment]
Geometry 2 released: https://github.com/ros/rosdistro/pull/26309

**Comment by rhaschke** [comment]
Finally, the release PR is out: https://github.com/ros/rosdistro/pull/26484

**Comment by RicoJia** [comment]
>     * `load_parameters: unable to set parameters (last param was [/move_group/planning_scene_monitor/publish_transforms_updates=True]): cannot marshal None unless allow_none is enabled`

I got the same error too. I got rid of it by adding a home pose in the setup_assistant. Was that the same issue for you? @mikeferguson Is it mandatory to add a home pose in the Noetic distro?
