### ISSUE TITLE
July 2020 Melodic Release

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit#2066]
## Timeline
1. May 7 - Create Issue to decide on issues
1. May 15 - Issues picked and PR(s) for backports created (jog_arm and other fixes)
1. June 1 - Backport PR(s) merged
1. July 1 - Code freeze of melodic-devel
1. July 15 -  Cut release
1. ??? - Sync happens and release is in the wild

## Backports Discussion
For our July Melodic release, I'd like to release the jog_arm feature.  There are two ways we can go about this, either we copy the existing state of jog-arm into melodic-devel or we backport all the PRs that went into jog-arm.

Also here are some bug fixes and smaller PRs that happened recently based on the instructions @v4hn linked to.  To try to figure out what differs here is the output of a git log command showing the difference.  We need to decide which ones of these we want to backport.  I've removed anything jog_arm and subframes from this list:

### Feature Backports
* [x] moveit_servo
* [x] MoveItCpp

### Bugfix Backport PRs 
* [x] Large bug-fix backport (#2080)
* [x] PlanningSceneDisplay speedup backport: (#2102)
* [x] FloatingJointModel::getStateSpaceDimension return value to 7 (#1424)
* [x] jog_arm recent changes (#2162)

### Backported Fixes

* Fix errors: catkin_lint 1.6.7 (#1987)
* Modernize Travis config (#1999) : Changes backported here: https://github.com/ros-planning/moveit/pull/2001
* Travis: send emails to author/committer : Changes backported here: https://github.com/ros-planning/moveit/pull/2001 
* remove unused angles.h includes (#1985)
* [ci] configure travis to report success before code-coverage finishes (#2041)
* Fix mesh_filter test (#2044)
* add tests for move_group interface (#1995)
* run shadow-fixed for main branches (#2012)
* fix ordering of request adapters (#2053)
* RS: add interfaces to zero and remove dynamics (#2054)
* totg: add a correct time parameterization for 1-waypoint trajectories (#2054)
* commander: python3 fix (#2030)
* add use_rviz to demo.launch in setup_assistant (#2019)
* MP display: planning attempts are natural numbers (#2076)
* fix signal for planning_attempts (#2082) 
* Wait and check for the grasp service (#2077)
* add aux check for shared-ptr (#2077)
* Added support for PS4 joystick (#2060)
* Check for empty quaternion message (#2089)
* PlanningSceneDisplay speedup (#2049)
* FloatingJointModel::getStateSpaceDimension return value to 7 (#2106)

## Tasks (with owners)
 - [x] Create an issue to track release - @tylerjw 
 - [x] Plan the possible date - @tylerjw
 - [x] Decide on what will be backported - @rhaschke / @v4hn  
 - [x] Create backport PRs - @tylerjw 
 - [x] Merge backport PRs - @rhaschke / @v4hn 
 - [ ] Move `reviewed-for-backport` tag - @v4hn 
 - [x] Notify release section of discourse - @tylerjw  
 - [x] Run buildfarm (prerelease) tests - @tylerjw 
 - [x] Update changelogs - @tylerjw  
 - [x] Create tag with version number - @tylerjw  
 - [x] Update versions in package.xml - @tylerjw  
 - [x] Run bloom - @tylerjw  
 - [x] Publish release notes on moveit.ros.org - @tylerjw  
 - [x] Post to MoveIt Discourse - @tylerjw  

## Updates
* Changed backport list to reflect new PR
* Add feature backport PRs
* Update bug fix backports
* Update after bug fix backports was merged
* Remove clang-tidy PR list as we discussed they are not getting backported
* Add recent jog-arm changes to backport list
* Changed timeframe as backports took longer than I originally expected
* Change tasks to be assigned to me

**Comment by v4hn** [comment]
Thanks for starting the issue.

Please look at "Consider backporting" in [our guidelines](https://moveit.ros.org/documentation/contributing/pullrequests/) for an alternative listing of relevant commits and explanations on the `reviewed-for-backport` branch.

As mentioned in https://github.com/ros-planning/moveit_msgs/issues/71 , we did not break the message format in melodic yet for subframes.
I would propose to avoid this altogether and not backport the feature.
If we backport it, the new origin pose should also be included (not fully merged yet) and @felixvd currently works on some more semantic changes...
Part of the commits related to it are prior to the backport branch by now,
so you'll have to look at them again if we really want to add it.

**Comment by tylerjw** [comment]
Would a September release of Melodic be a better target for Subframes then?  That would simplify the July release to be just Jog-arm and bug fixes.

**Comment by AndyZe** [comment]
What I would recommend is copy/paste the whole jog_arm folder into moveit_experimental in a single commit, instead of trying to cherry-pick all the related changes.

I think that makes sense because there would be quite a few commits to cherry-pick. jog_arm doesn't exist in Melodic at all

**Comment by davetcoleman** [comment]
Thanks for taking this initiative @tylerjw 

Per https://github.com/ros-planning/moveit/issues/1747#issuecomment-624673572, PickNik will lead the actual release steps this time

**Comment by tylerjw** [comment]
I adjusted the above message to remove the subframes feature from this release.  We will revisit it on the next release.

For jog arm there are two options for the merge:

1. Merge each PR that has created jog_arm
2. Copy the folder in its current state into melodic-devel

@rhaschke please let us know what your preference is so we can prepare the PR for it.

For non-jog_arm related changes since the latest release, I'll make a list so we can decide which ones should be back-ported and update the description above.

**Comment by v4hn** [comment]
> Merge each PR that has created jog_arm

Following this approach, there should of course be only one pull-request combining all commits in `master`.
As jog_arm is very much isolated and all related commits should *only ever* have touched the respective folders, I guess it should be a matter of `git log -S` or similar to find and pick all commits.
I would strongly prefer that.

**Comment by v4hn** [comment]
> Would a September release of Melodic be a better target for Subframes then?

First point for the maintainer meeting. I believe there are different stances on whether we can still break messages in melodic.

**Comment by tylerjw** [comment]
Ok, here are all the changes that have touched the jog_arm folder as of now.  Please look through these and let me know if any of these will be a problem to backport?

7306d1df7 llvm-namespace-comment
ad88e18ae [jog_arm] Keep updating joints, even while waiting for a valid command (#2027)
4d3062164 [jog_arm] Fix param logic bug for self- and scene-collision proximity thresholds (#2022)
3be547d1c [jog_arm] Split collision proximity threshold (#2008)
18715e1c2 [jog_arm] Fix valid command flags (#2013)
d4ade526e Fix some clang tidy issues (#2004)
2627d7eed Pause/stop JogArm threads using shared atomic bool variables
85be9f8f2 Add pause/unpause flags for jog thread
2e4c08d52 Verify valid joints by filtering for active joint models only
d168cd9ea Remove redundant joint state increments
ef16990f7 Wait for initial jog commands in main loop
13bf03e93 Remove duplicate collision check in JogArm (#1986)
8946d266b [jog_arm] Add a binary collision check (#1978)
6d3b89904 [jog_arm] Publish more detailed warnings (#1915)
e34a07d89 jog_arm: use wait_for_service() to fix flaky tests (#1946)
8b2a08145 Fix versioning (#1948)
5327e4197 [jog_arm] SRDF velocity and acceleration limit enforcement (#1863)
ba4b60e07 Replace namespaces robot_state and robot_model with moveit::core (#1924)
6eaa75d69 JogArm C++ API fixes (#1911)
26863598b [jog_arm] a ROS service to enable task redundancy (#1855)
7193a4ea2 Fix segfault with uninitialized JogArm thread (#1882)
15cb1a2dc Add warnings to moveit_jog_arm low pass filter (#1872)
f6308f405 Fixup: Use CMAKE_CXX_STANDARD to enforce c++14 for portability (#1607)
83728716e Fix the publishWarning() functionality
75b79108f Always provide the end effector transform, not just while robot is jogging
49892146c [jog_arm] Rework the halt msg functionality (#1868)
4f996c71a [jog_arm] Various small fixes (#1859)
1389df263 [jog_arm] Improve formatting in comments
75104b0d4 jog_arm: prevent a crash at velocity limit (#1837)
2a8559503 [jog_arm] Remove scale/joint parameter (#1838)
cd16a5033 [jog_arm] Pass planning scene monitor into cpp interface (#1849)
92032b516 Move attribution below license file, standardize with MoveIt (#1847)
3a57141b4 Reduce console output warnings (#1845)
546d6e052 Fix command frame transform computation (#1842)
06a9e4bea moveit_jog_arm: fix dependencies + catkin_lint issues
844a02128 update link transforms before calling checkCollision on robot state in jog_arm (#1825)
bc752b7c8 Add atomic bool flags for terminating JogArm threads gracefully (#1816)
e0b4f854e moveit_jog_arm: Get transforms from RobotState instead of TF (#1803)
76c16e613 jog_arm: add a C++ API (#1763)
b35e64084 Merge #1773: Fix compiler warnings
8bdf9e57b fix unused parameter warnings
4ff87ded5 Update license formatting (#1764)
0924e99de Unify jog_arm package to be C++14 (#1762)
2bef2b62a Fix jog_arm segfault (#1692)
ff8f1d850 Fix double mutex unlock (#1672)
ff71fc44b Rename jog_arm->moveit_jog_arm (#1663)

**Comment by rhaschke** [comment]
1. I think we agreed - already multiple times - that we should only backport bug fixes. IMHO this excludes both, jog arm and subframes support from melodic. We should have some features only in master / noetic that will motivate people to migrate :wink:

2. I think separating the processes of selecting individual commits and actually filing PRs for backports is not very sensible: In order to decide, you need to inspect the commits anyway (for API changes). If you do so, you can also directly apply the commit to your local MoveIt, test-compile it, and finally file the PR as Michael has done recently.
Such a preselection only makes sense on an abstract level, say like we want backporting of features / bug fixes A, B, and C (as Tyler started out with).

**Comment by tylerjw** [comment]
In response to #2, I should have been more clear.  I was hoping that you would look over the list and call out any you know you specifically don't want backported.

I figured we'd still have a backport PR where we would test the ones we thought were a good idea and potentially remove some we find are not from that list then too.

**Comment by tylerjw** [comment]
In response to 1, I do like the idea of getting people to migrate to Noetic and think subframes would be excellent for this as it breaks the messages API.

Jog arm (to my knowledge) doesn't break any existing API in MoveIt and is a straightforward new feature.  My motivation for getting it released with MoveIt is we are supporting a client right now that is using it and having it released would be helpful because it would create the jog_arm melodic rosdistro symbols to be able to install it.  This would greatly simplify us distributing debians for jog_arm.

**Comment by v4hn** [comment]
> I think we agreed - already multiple times - that we should only backport bug fixes.

I am rather convinced I did not agree to this and I'm clearly not alone.
Once noetic is out and MoveIt users actually started using it, I will of course change my opinion.

We agreed *not to break API*.

>  I was hoping that you would look over the list and call out any you know you specifically don't want to be backported.

- you missed that the project was originally added under the name of `jog_arm` and thus you missed a number of commits (as you would have noticed if you tried cherry-picking :) )

- a number of clang-tidy fixes swept through the whole code base in one commit.
  If they apply cleanly just add them, sure thing. If they don't, you can trim the commits to touch the `jog_arm` package only (and adjust the commit message accordingly).

**Comment by tylerjw** [comment]
> * you missed that the project was originally added under the name of `jog_arm` and thus you missed a number of commits (as you would have noticed if you tried cherry-picking :) )

I didn't know that, thank you.  I'll see if I can figure out how to do the cherry-pick.

My comment you quoted was directed at the list in the description at the top of non jog_arm changes.

For the clang-tody fixes, that is a good point.

**Comment by tylerjw** [comment]
I spent an hour or so trying to do cherry-picks and then an interactive rebase searching through the history to find the right place to insert each commit to get the jog_arm stuff to cleanly apply... and so far have failed.

@v4hn do you have any tricks for doing this with such a huge set of changes?  I'm sadly approaching the opinion that cleanly applying jog_arm might be too hard and therefore we should just target Noetic with it.  :cry: 

You said something about partially applying changes.  Do you know of any way to ask git to apply some changes to only the files in a certain directory?

**Comment by tylerjw** [comment]
I created a PR for backporting changes that were clean to apply: https://github.com/ros-planning/moveit/pull/2080

As to the clang-tidy fixes, they touch so much of the code I wasn't able to get them to cleanly apply.  This mostly was because there are previous clang-tidy changes that are also not backported.  Is the normal approach here to wait for the next release for repository wide changes like these?

**Comment by v4hn** [comment]
> As to the clang-tidy fixes, they touch so much of the code I wasn't able to get them to cleanly apply.
> This mostly was because there are previous clang-tidy changes that are also not backported.

The previous tidy commands also resulted in a lot of conflicts and I ultimately decided it wasn't worth the effort.
Instead, I fixed other conflicts because of the missing tidy commits by hand.

> @v4hn do you have any tricks for doing this with such a huge set of changes?
> I'm sadly approaching the opinion that cleanly applying jog_arm might be too hard and therefore we should just target Noetic with it. cry

This is really straight-forward with the right tool! But also badly documented if you don't know it. -.- https://github.com/newren/git-filter-repo works well for me:

```
git clone https://github.com/ros-planning/moveit
cd moveit
git filter-repo --path moveit_experimental/moveit_jog_arm/ --path moveit_experimental/jog_arm --refs master
git rebase melodic-devel
```

Make sure to try on fresh clones to avoid scrambling your workspace repository.

**Comment by tylerjw** [comment]
I created #2083 for the jog_arm backport.  Unfortunately, it looks like it depends on this change: https://github.com/ros-planning/moveit/pull/1584 which to me looks like it introduces breaking API changes.  Am I interpreting that correctly or is there another way to make this work?  

@AndyZe would there be a way to modify jog_arm to make it work with the old internal API easily for melodic-devel?

**Comment by henningkayser** [comment]
> I created #2083 for the jog_arm backport. Unfortunately, it looks like it depends on this change: #1584 which to me looks like it introduces breaking API changes. Am I interpreting that correctly or is there another way to make this work?

@tylerjw fixed it with https://github.com/ros-planning/moveit/pull/2083/commits/23947b2c180ec47dcc836dc35faceca5085c3e0e
I don't think that there would be any other issues with the backport.

**Comment by v4hn** [comment]
Looking at this again, the timeline looks weird:

    June 15 - Create shadow repo for testing and post on discord
    July 1 - Run bloom

I might have misunderstood something here,
but to get into `ros-shadow-fixed`, you have to *run bloom*?
Or did you mean something else by "shadow repo"?

**Comment by tylerjw** [comment]
> I might have misunderstood something here,
> but to get into `ros-shadow-fixed`, you have to _run bloom_?
> Or did you mean something else by "shadow repo"?

I think this is just my misunderstanding of our release guide.  I read that those were steps we did in that order even though I don't understand what they mean.  Please advise what it should be?

**Comment by tylerjw** [comment]
@v4hn can you move the `reviewed-for-backport` as all backports for this release have been merged?  I don't think I have the permissions to do that.

**Comment by v4hn** [comment]
> can you move the reviewed-for-backport

done. Doing so, I noticed d3bd523ee0ec296656cf964c1b7af190e3bfe9f9 is not ported yet and @simonschmeisser [wants to backport his RViz speedup too](https://github.com/ros-planning/moveit/pull/2049#issuecomment-632001140).
We will definitely not postpone the schedule for new backports, but I guess we will have another backports request to be merged before code freeze.

> I think this is just my misunderstanding of our release guide. I read that those were steps we did in that order even though I don't understand what they mean. Please advise what it should be?

I just noticed the timeline collides with WMD too.
[WMD2020 is scheduled on June 2](https://discourse.ros.org/t/world-moveit-day-hackathon-june-2nd/13974). I would propose to have the `melodic-devel` freeze (and discourse announcement) on June 15 and release/bloom on July 1st.
@rhaschke comments, additions, misunderstandings?

**Comment by tylerjw** [comment]
@v4hn I'm ok with pushing back code freeze and backporting more stuff and giving opportunities for WMD improvements to make it in.  

I had previously assumed we'd want to let most new changes sit in master for a couple of months as a matter of policy to make it easier to have confidence in the stability of the release.  I want to push releases out every quarter though so the backporting isn't so painful and so improvements contributors submit are released in a reasonable amount of time.

My other thought was that this Melodic release wouldn't matter much to WMD and after this goes out we'd all mostly focus on Noetic and continue to only backport to Melodic things that were easy to backport (like the two PRs you referred to).  This is a good justification for getting more in this release as we might be less motivated after we start to focus on Noetic.  

I'm torn on what the right policy is here.

**Comment by v4hn** [comment]
> I had previously assumed we'd want to let most new changes sit in master for a couple of months as a matter of policy to make it easier to have confidence in the stability of the release.

Makes sense as well. Having a known and patched write-past-buffer (which has been in there for a long time) in a release would make my stomach cringe though..

> My other thought was that this Melodic release wouldn't matter much to WMD

Unless someone wants to contribute something specifically to melodic (quite a likely goal for MoveIt *users*).
I don't mind not including these things in the upcoming release yet, but the branch freeze would be unfortunate...
(or we just handle it on a case-by-case basis, as we did in the past)

> and after this goes out we'd all mostly focus on Noetic

Muhahaha.

> and continue to only backport to Melodic things that were easy to backport (like the two PRs you referred to).
> This is a good justification for getting more in this release as we might be less motivated after we start to focus on Noetic.

I expect at least half a year of overlap, possibly more.
Together with your release schedule that means it is surely not the last release that includes bigger contributions from `master`.

**Comment by simonschmeisser** [comment]
It's not super important for me to have the PlanningSceneDisplay speedups included in the next release as we build from source. I'll open a backport PR anyway as I need a branch to build from

**Comment by tylerjw** [comment]
@simonschmeisser thank you for offering to open a backport PR for your change.  If others agree it is simple enough we can get it in this release, if not we can target it for the next.

> Having a known and patched write-past-buffer (which has been in there for a long time) in a release would make my stomach cringe though...

@v4hn yea, mine too.  I don't think to fix that will hurt anyone and we can probably include it in this one easily enough.

**Comment by tylerjw** [comment]
> and after this goes out we'd all mostly focus on Noetic
> Muhahaha.

my feelings exactly... :laughing: :speak_no_evil: 

In all seriousness, the more we can get users on Noetic (if that's possible in WMD) the nicer it will be for all of us.

**Comment by tylerjw** [comment]
Coming back here and iterating on this, I'm done changing jog_arm for the time being and would like to back-port the recent changes before this release.

**Comment by tylerjw** [comment]
@v4hn I believe all the backports for this release have been merged now.  Do you mind moving the `reviewed-for-backport` tag?

I'll start doing the next steps after that myself.  We should open a new issue where people can start listing the changes they want to backport to the next meldoic release and when it should be ( September? ).

**Comment by tylerjw** [comment]
To confirm the version for this release is 1.0.5 ?

**Comment by rhaschke** [comment]
Yes, 1.0.5 will be the next Melodic release. Please file a PR before committing your first changelog.
Have a look at previous changelogs to get an idea of the targeted level of detail and the grouping of commits.

**Comment by tylerjw** [comment]
:+1: 

I'm working on the changelists and a PR was my plan for that.  I'm also running the pre-release tests.  Is there anything I need to do to show that I ran them and they worked?

**Comment by rhaschke** [comment]
> I'm also running the pre-release tests. Is there anything I need to do to show that I ran them and they worked?

No, I trust your word!

**Comment by tylerjw** [comment]
Here is the PR for the Changelists... there were allot of changes: https://github.com/ros-planning/moveit/pull/2184

For the pre-release tests... these two are failing... :cry: 
```
moveit_ros_planning_interface/MISSING-rostest-test_move_group_interface_cpp_test.xml: 1 tests, 0 errors, 1 failures, 0 skipped
moveit_ros_planning_interface/MISSING-rostest-test_moveit_cpp_test.xml: 1 tests, 0 errors, 1 failures, 0 skipped
```

I'll look into figuring out why next.  If anyone has tricks for debugging tests failing in the pre-release process please let me know.  These are two tests that I've contributed to this time around so it is probably my fault they are failing.

**Comment by rhaschke** [comment]
I will have a look into the changelogs tomorrow.
The pre-release tests run in a docker container, right? Try to save those containers, re-enter them, and manually execute the test there.

**Comment by rhaschke** [comment]
I started a local build of melodic-devel as well an this is the outcome:
```
build/moveit_ros_perception/test_results/moveit_ros_perception/gtest-mesh_filter_test.xml: 48 tests, 0 errors, 2 failures, 0 skipped
build/moveit_servo/test_results/moveit_servo/rostest-test_launch_servo_drift_dimensions_service_test.xml: 1 tests, 0 errors, 1 failures, 0 skipped
build/moveit_servo/test_results/moveit_servo/rostest-test_launch_servo_halt_msg_test.xml: 1 tests, 0 errors, 1 failures, 0 skipped
build/moveit_servo/test_results/moveit_servo/rostest-test_launch_servo_msg_reception_test.xml: 1 tests, 0 errors, 1 failures, 0 skipped
build/moveit_servo/test_results/moveit_servo/rostest-test_launch_servo_vel_accel_limits_test.xml: 1 tests, 0 errors, 1 failures, 0 skipped
```
The mesh filter test fails as follows:
```xml
<testcase name="float/7" value_param="3.5" status="run" time="0.086" classname="float_test/MeshFilterTestFloat">
<failure message="/tmp/ros/src/moveit/moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp:234 The difference between filtered_depth[idx] and gt_depth[idx] is 3.599998950958252, which exceeds 1e-6, where filtered_depth[idx] evaluates to 3.599998950958252, gt_depth[idx] evaluates to 0, and 1e-6 evaluates to 9.9999999999999995e-07." type="">
<![CDATA[ /tmp/ros/src/moveit/moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp:234 The difference between filtered_depth[idx] and gt_depth[idx] is 3.599998950958252, which exceeds 1e-6, where filtered_depth[idx] evaluates to 3.599998950958252, gt_depth[idx] evaluates to 0, and 1e-6 evaluates to 9.9999999999999995e-07. ]]>
</failure>
</testcase>
```

The others seem to fail due to an pytest issue:
```
Traceback (most recent call last):
  File "/tmp/ros/src/moveit/moveit_ros/moveit_servo/test/python_tests/drift_dimensions_service/test_drift_dimensions_service.py", line 4, in <module>
    import pytest
  File "/usr/lib/python2.7/dist-packages/pytest.py", line 13, in <module>
    from _pytest.fixtures import fixture, yield_fixture
  File "/usr/lib/python2.7/dist-packages/_pytest/fixtures.py", line 842, in <module>
    class FixtureFunctionMarker(object):
  File "/usr/lib/python2.7/dist-packages/_pytest/fixtures.py", line 844, in FixtureFunctionMarker
    params = attr.ib(convert=attr.converters.optional(tuple))
TypeError: attrib() got an unexpected keyword argument 'convert'
```
I'm using the ros-testing binaries. Maybe pytest did a recent release, which is broken (but not yet synced).
If that's the reason, Travis should fail as well. I retriggered the corresponding build job:
https://travis-ci.com/github/ros-planning/moveit/jobs/356539442

**Comment by rhaschke** [comment]
The pytest errors on my machine were related to an unrelated, incompatible update of the attr package on my machine:
https://stackoverflow.com/questions/58189683/typeerror-attrib-got-an-unexpected-keyword-argument-convert
Sorry for the noise.

**Comment by AndyZe** [comment]
We should delete those anyway, they're redundant with C++ tests now. I can make a PR unless one of you beats me to it. (Assuming this is miveit_servo)

**Comment by rhaschke** [comment]
Would be great if we could get rid off the ros_pytest dependency :wink:

**Comment by AndyZe** [comment]
A PR to delete the Python tests is here:  https://github.com/ros-planning/moveit/pull/2186

**Comment by v4hn** [comment]
> I believe all the backports for this release have been merged now. Do you mind moving the reviewed-for-backport tag?

I looked at it again and came up with #2190 and #2189 . Let's keep the tag where it is until both are merged (the latter one after the release). I documented the target commit in the new pull-request.

**Comment by tylerjw** [comment]
@v4hn thank you for doing that.  Those both look reasonable (and good) to backport (especially the first one).  Thank you for checking on which ones were missing.

**Comment by rhaschke** [comment]
Hi @tylerjw,
regarding your pre-release test and the two failing unit tests: Looks like these two tests are failing since May 2020 (#2080) already on the ROS buildfarm:
http://build.ros.org/job/Mdev__moveit__ubuntu_bionic_amd64/changes
The reason is that both of them,
`moveit_ros/planning_interface/test/move_group_interface_cpp_test.test` and 
`move_group_interface_cpp_test`
depend on `panda_moveit_config` (instead of moveit_resources). Should be easy to fix.

**Comment by tylerjw** [comment]
With this PR the pre-release tests pass: https://github.com/ros-planning/moveit/pull/2197

**Comment by tylerjw** [comment]
This now passes the pre-release tests.

**Comment by tylerjw** [comment]
I rebased and updated the changelogs with the recent minor changes.  If @rhaschke approves, I will merge the changelogs tomorrow (July 8th) and run bloom.

**Comment by tylerjw** [comment]
I received the permissions needed to bloom a release and I ran it for this.  Here is the rosdistro PR: https://github.com/ros/rosdistro/pull/25816

**Comment by tylerjw** [comment]
Does anyone know how the changelogs in the ros index get populated.  The date for the last few releases are there but there are no changelogs.  Should I have put some entries in the moveit meta package?

https://index.ros.org/p/moveit/github-ros-planning-moveit/#melodic

**Comment by v4hn** [comment]
It seems Isaac actually copied the changelogs together and added everything relevant to the meta package CHANGELOG as well as to each individual package. Looks like neither Robert nor you followed in that tradition.

**Comment by tylerjw** [comment]
I'm sorry, should we add that to the instructions for a releases?

I am writing a summary of the release to announce it on discord soon.  In that I'll attempt to point out the amazing work that people have contributed that is now (or soon to be) available in the distribution release.  I'll post it here first to get feedback on it if anyone cares to comment.

**Comment by v4hn** [comment]
> I'm sorry, should we add that to the instructions for a releases?

I guess we simply gave up on that particular tradition..
If you think it's worthwhile to pick it up again, create a pr to document it.

> I am writing a summary of the release to announce it on discord soon.

Cool!

**Comment by rhaschke** [comment]
Indeed, I didn't follow this tradition (because I wasn't aware of it). The detailed changelogs are available for all individual packages though. I don't think we need to copy those. Having a summary on discourse would be great. Thanks for your work, @tylerjw.

**Comment by tylerjw** [comment]
Discourse announcement draft:

# MoveIt Melodic Release (1.0.5)
Many of the awesome features and bug fixes only available to people building MoveIt on master from source are coming to an apt repo near you.

## moveit_servo (Formally moveit_jog_arm)
Real-time robot arm control.  [So cool, we even got a smile from a famous person while using it.](
https://www.youtube.com/watch?v=uwYtwQtoOh0).  [There is an tutorial for getting started with it.
](https://ros-planning.github.io/moveit_tutorials/doc/arm_jogging/arm_jogging_tutorial.html)
![thank_you_servo](https://user-images.githubusercontent.com/2490389/87839926-4d6fb600-c85a-11ea-958e-3296ca05a020.gif)

## moveitcpp
There is a new high level API for users who have more real-time requirements.  [Here is the tutorial for using it.](https://ros-planning.github.io/moveit_tutorials/doc/moveit_cpp/moveitcpp_tutorial.html)

## Other features
* Allow to parameterize input trajectory density of Time Optimal trajectory generation (#2185)
* Added support for hybridize/interpolate flags in ModelBasedPlanningContext via ompl_planning.yaml (#2171)
* Improve responsiveness of PlanningSceneDisplay (#2049)
* PlanningComponent: Load plan_request_params (#2033)
* Improve rviz GUI to add PlanningScene objects. Ask for scaling large meshes. (#2142)
* PlanningSceneDisplay speedup (#2049)
* Added support for PS4 joystick (#2060)
* Add use_rviz to demo.launch in setup_assistant (#2019)

## Bug fixes
* Behaviors (#2113, #2054, #2157, #2076, #2082, #2120)
* Segfaults (#2104, #2106)
* Memory leaks (#2138)
* Python 3 (#2030)

## Contributors
* Andy Zelenak
* Constantinos
* Felix von Drigalski
* Henning Kayser
* Jafar Abdi
* Jere Liukkonen
* John Stechschulte
* Mark Moll
* Michael Görner
* Patrick Beeson
* Robert Haschke
* Simon Schmeisser
* TrippleBender
* Tyler Weaver
* Yeshwanth
* Wolfgang Merkt

**Comment by v4hn** [comment]
> “If you don’t like unit testing your product, most likely your customers won’t like to test it either.” – Anonymous

Not sure our current coverage justifies the quote. ;)

> There is a new high level API for users who have more real-time requirements.

I would propose "users who want convenient access to MoveIt's functionality via C++ classes".
Planning with OMPL will not magically become real-time. :D

> * Improve rviz GUI to add PlanningScene objects. Ask for scaling large meshes. (#2142)

This could be easily confused with the later features to add primitives.
That feature will only be available after the next round of reviews (& backports) though.

> ## Contributors

Sorting by first name seems weird, but nobody cares.

**Comment by tylerjw** [comment]
>  “If you don’t like unit testing your product, most likely your customers won’t like to test it either.” – Anonymous
> Not sure our current coverage justifies the quote. ;)

I see how this reads now.  I was hoping for a fun goofy feeling to this announcement, but I really am bad at conveying that emotion in writing.



> Planning with OMPL will not magically become real-time. :D

True, and here is an example of me using real-time confusingly when I give others grief for doing that.

I'll revise it based on your feedback, thank you.

**Comment by tylerjw** [comment]
> Sorting by first name seems weird, but nobody cares.

I fixed it, it was weird.  This happened because I went through the changelists and put the names in a text file on separate lines and then called sort on that text file and removed duplicates.  Other than doing it manually I'm not sure of an easy way to sort a list alphabetically by the last word.  There is probably some magic sed command that'd do that.

**Comment by tylerjw** [comment]
> This could be easily confused with the later features to add primitives. That feature will only be available after the next round of reviews (& backports) though.

I reworded this feature, lmk if that captures what the feature is that did make it into this release?

Thank you for the feedback.  By writing this I realized how bad I am at writing marketing type cheery written announcements.  I learned from my last post (about the jog_arm rename) was a bit dry, I hope the gif helps with that.

**Comment by v4hn** [comment]
> I reworded this feature, lmk if that captures what the feature is that did make it into this release?

Good enough.

> By writing this I realized how bad I am at writing marketing type cheery written announcements.

I believe you have good mentors at PickNik. ;)

> I learned from my last post (about the jog_arm rename) was a bit dry, I hope the gif helps with that.

If Dave and/or Andy approve the statement it's fine. Guess I've just seen it too often by now. :-)

**Comment by henningkayser** [comment]
Maybe also reference the JogArm tutorial and add a quick one-sentence intro for those who don't know about it yet. Otherwise, I like highlighting the features and changes like this without too many words :+1:

**Comment by tylerjw** [comment]
> Maybe also reference the JogArm tutorial

There is a link to the jogarm tutorial.

**Comment by tylerjw** [comment]
latest Discourse announcement draft (thank you @nbbrooks for the review):

# MoveIt Melodic Release (1.0.5)
Many of the awesome features and bug fixes only available to people building MoveIt on master from source are coming to an apt repo near you. Along with all these great features come bug fixes and some new tests that helped find those bugs.
## New features
### moveit_servo (Formally moveit_jog_arm)
Real-time robot arm control. [So cool, we even got a smile from a famous person while using it.](https://www.youtube.com/watch?v=uwYtwQtoOh0)
![thank_you_servo](https://user-images.githubusercontent.com/2490389/87839926-4d6fb600-c85a-11ea-958e-3296ca05a020.gif)
[Here is an tutorial for getting started with it. ](https://ros-planning.github.io/moveit_tutorials/doc/arm_jogging/arm_jogging_tutorial.html)
### moveit_cpp
There is a new high level API for users who want convenient access to MoveIt's functionality via C++ classes. [Here is the tutorial for using it.](https://ros-planning.github.io/moveit_tutorials/doc/moveit_cpp/moveitcpp_tutorial.html)
## Other features
* Allow parameterization of input trajectory density of Time Optimal trajectory generation (#2185)
* Add support for hybridize/interpolate flags in ModelBasedPlanningContext via ompl_planning.yaml (#2171)
* Improve responsiveness of PlanningSceneDisplay (#2049)
* Use plan_request_params in PlanningComponent (#2033)
* Ask for scaling large meshes in rviz (#2142)
* Speed up PlanningSceneDisplay (#2049)
* Add support for PS4 joystick (#2060)
* Add use_rviz to demo.launch in setup_assistant (#2019)
## Bug fixes
* Behaviors (#2113, #2054, #2157, #2076, #2082, #2120)
* Segfaults (#2104, #2106)
* Memory leaks (#2138)
* Python 3 (#2030)
## Contributors
* Jafar Abdi
* Patrick Beeson
* Constantinos
* Felix von Drigalski
* Michael Görner
* Robert Haschke
* Henning Kayser
* Jere Liukkonen
* Wolfgang Merkt
* Mark Moll
* Simon Schmeisser
* John Stechschulte
* TrippleBender
* Tyler Weaver
* Yeshwanth
* Andy Zelenak

**Comment by tylerjw** [comment]
I'll close this issue for now as it is released into the shadow repos.  We can now begin work on backporting (if you all haven't already) new changes into the next release.  I'll create a new issue for that release in the comming month.
