### ISSUE TITLE
Melodic backports

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit#2387]
Here is the list of changes since reviewed-for-backport on master:

 - [x] Start new joint_state_publisher_gui on param use_gui (#2257)
 - [x] add soname version to moveit_servo (#2266)
 - [x] Move constraint representation dox to moveit_tutorials (#2147)
 - [x] Update last_sent_command_ at ServoCalcs start (#2249)
 - [x] Add a utility to print collision pairs (#2275)
 - [x] fix some spelling errors in the ompl interface (#2279)
 - [x] Cleanup: Add a utility to print collision pairs (#2278)
 - [x] Replace $(find xacro)/xacro -> xacro (#2282)
 - [x] [maint] Remove kinetic from Travis CI testing (#2295)
 - [x] MSA: only write default_planner_config field if any is selected (#2293)
 - [x] [fix] Servo heap-buffer-overflow bug (#2307)
 - [x] Add comment to MOVEIT_CLASS_FORWARD (#2315)
 - [x] robot_description is already loaded in move_group.launch (#2313)
 - [x] Refactor velocity limit enforcement and add a unit test (#2260)
 - [x] Fix Servo thread interruption (#2314)
 - [x] MGC: Improve exception messages (#2318)
 - [x] Clean up Rviz Motion Planning plugin, add tooltips (#2310)
 - [ ] ikfast: add missing python dependencies **Doesn't seem to work on melodic, issues with condition attribute in package.xml**
 - [x] Install python scripts via catkin_install_python()
 - [x] Remove shebang line from moveitjoy_module.py
 - [ ] Adapt to API changes in geometric_shapes (#2324) **Probably shouldn't backport this**
 - [x] Remove custom copy-assignment operator for DistanceResultsData
 - [x] perception: add missing dependency to OpenMP
 - [x] Silent deprecation warnings of gtest's typed test suites
 - [x] Handle multiple link libraries for FCL (#2325)
 - [ ] Fix clang-tidy warning (#2334)  **Edits lines that don't exist on melodic-devel**
 - [ ] Fix some clang-tidy issues on Travis (#2337)  **merge conflicts I don't understand**
 - [x] [fix] Segfault when editing pose in moveit_setup_assistant (#2340)
 - [x] Fix "Clear Octomap" button, disable when no octomap is published (#2320)
 - [x] moveit_cpp: more informative error message, cover another potential failure condition. (#2336)
 - [x] MSA: Update RobotState *before* visualization
 - [x] remove commented, copy-pasted code
 - [x] Use PlanningScene's RobotState for postures
 - [ ] Fix ROS namespacing in moveit_commander's PSI (#2347)
 - [x] Reorder buttons in GroupEditWidgets
 - [x] Replace dummy QWidgets with QSpacerItems
 - [x] Use QStackedWidget instead of QWidget+QStackedLayout
 - [x] Remove released upstream packages from docker files
 - [x] Increase minimal window size
 - [x] Cleanup Qt includes
 - [x] Cleanup ROS includes
 - [ ] Remove diagnostics macros
 - [x] Fix unused-parameter warnings
 - [x] MSA: Allow showing both, visual and collision geometry (#2352)
 - [x] MSA: Fix group editing (#2350)
 - [x] move_group: simplify test launch files
 - [x] A library for servoing toward a moving pose (#2203)
 - [ ] Depend on ros-noetic-fcl (0.6) in Noetic (#2359)
 - [x] Make GILReleaser exception-safe (#2368 
 - [x] Python interface improvements. Fix #1966, add enforceBounds (#2356)
 - [x] Fix ordering of windup args to control_toolbox::Pid (#2370)
 - [x] MSA launch files: fix indentation (#2371)
 - [x] Add test for PlanningContextManager in ompl interface (#2248)
 - [x] Update .github files (#2380)
 - [x] Fix servo trajectory point timestamping (#2375)
 - [x] Change servo namespacing logic (#2354)
 - [x] Cleanup current state handling in servo (#2372)

Here we go again.  @rhaschke @v4hn @felixvd I could use help figuring out what we can (and cannot) back port, making the backports, reviewing them, merging and testing them so we can cut a melodic release with the next Noetic release on Nov 20th.

## Edits
* Removed the version bump and noetic changelog commits that don't need to be backported.
* Remove codecov.io changes (we don't run codecov on melodic-devel)
* Remove codeownsers file changes (file doesn't exist on melodic-devel)

**Comment by felixvd** [comment]
What's the best way to do this? A separate branch from `melodic-devel` on the main repo to test commits on, and then fast-forwarding `melodic-devel` to it after the necessary commits were cherry-picked?

**Comment by tylerjw** [comment]
I got started on it and will submit a pull request with a handful of these that are easy to backport with some notes about the ones that I couldn't figure out.  Basically what you do is create a new branch (like you would for any pull request) that is based on melodic-devel and then start cherry-picking these commits onto that branch.  You can then submit a normal PR except you target melodic-devel.  When it is accepted we do a rebase merge and it will just place those commits on the melodic-devel branch.

**Comment by tylerjw** [comment]
I find it helpful to have a second checkout of moveit on master so I can look through the git log of it easily to find the commit hashes and then cherry-pick those commits into the melodic-devel setup I'm testing with.

**Comment by tylerjw** [comment]
Here are a set of backports I found straightforward to apply: https://github.com/ros-planning/moveit/pull/2391

**Comment by tylerjw** [comment]
This is now done, I will release these changes today onto melodic and move the reviewed-for-backport tag after the release.
